#!/bin/bash
echo "----------------------------------------------------"
echo "Running git pre-commit hook, Running ktlintReport..."
echo "----------------------------------------------------"

stagedFiles=$(git diff --staged --name-only)

./gradlew ktlintReport

exitCode=$?

if [ "$exitCode" = 0 ] ; then
    echo "Static analysis found no issues — well done!"

    exit 0
else
    echo "----------------------------------------------------------------------------"
    echo 1>&2 "Static analysis detected issues that must be resolved before committing"
    echo "See your project /build/ktlintReport/ktlintReport.xml"
    echo "----------------------------------------------------------------------------"

    exit 1
fi
